"use client";

import { useState, useCallback, useMemo } from "react";
import { Plus, Send, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { PlatformIcon } from "./platform-icon";
import {
  PendingDistributionAccordionItem,
  type PendingDistribution,
} from "./pending-distribution-accordion-item";
import { cn } from "@/lib/utils";
import type { ContentAccountWithPlatform } from "@/lib/supabase/types";

// ============================================================================
// TYPES
// ============================================================================

interface PendingDistributionsTabProps {
  accounts: ContentAccountWithPlatform[];
  pendingDistributions: PendingDistribution[];
  onAddDistribution: (distribution: Omit<PendingDistribution, "id">) => void;
  onUpdateDistribution: (id: string, updates: Partial<PendingDistribution>) => void;
  onRemoveDistribution: (id: string) => void;
}

// ============================================================================
// COMPONENT
// ============================================================================

export function PendingDistributionsTab({
  accounts,
  pendingDistributions,
  onAddDistribution,
  onUpdateDistribution,
  onRemoveDistribution,
}: PendingDistributionsTabProps) {
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [selectedAccountIds, setSelectedAccountIds] = useState<string[]>([]);
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  // Get accounts that haven't been added yet
  const availableAccounts = useMemo(() => {
    const usedAccountIds = pendingDistributions.map((d) => d.accountId);
    return accounts.filter((account) => !usedAccountIds.includes(account.id));
  }, [accounts, pendingDistributions]);

  // Group available accounts by platform
  const accountsByPlatform = useMemo(() => {
    return availableAccounts.reduce((acc, account) => {
      const platformName = account.platform?.display_name || "Other";
      if (!acc[platformName]) {
        acc[platformName] = [];
      }
      acc[platformName].push(account);
      return acc;
    }, {} as Record<string, ContentAccountWithPlatform[]>);
  }, [availableAccounts]);

  // Get account info from ID
  const getAccountInfo = useCallback(
    (accountId: string) => {
      return accounts.find((a) => a.id === accountId);
    },
    [accounts]
  );

  // Toggle account selection
  const toggleAccount = useCallback((accountId: string) => {
    setSelectedAccountIds((prev) =>
      prev.includes(accountId)
        ? prev.filter((id) => id !== accountId)
        : [...prev, accountId]
    );
  }, []);

  // Handle adding distributions
  const handleAddDistributions = useCallback(() => {
    selectedAccountIds.forEach((accountId) => {
      onAddDistribution({
        accountId,
        format: null,
        caption: null,
        scheduledAt: null,
        postedAt: null,
        status: "draft",
        platformPostUrl: null,
        internalNotes: null,
        createPerformanceCheckTasks: true, // Default to ON
      });
    });
    setSelectedAccountIds([]);
    setShowAddDialog(false);
    // Expand the first newly added distribution
    if (selectedAccountIds.length > 0) {
      // The ID will be generated by the parent, so we need to wait for it
      // For now, we don't auto-expand
    }
  }, [selectedAccountIds, onAddDistribution]);

  // Toggle accordion expansion (allows multiple expanded)
  const handleToggle = useCallback((id: string) => {
    setExpandedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  return (
    <>
      <div className="space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-medium">Distributions</h3>
            <p className="text-small text-text-muted">
              Add platforms where this post will be published
            </p>
          </div>
          <Button onClick={() => setShowAddDialog(true)} disabled={availableAccounts.length === 0}>
            <Plus className="w-4 h-4 mr-2" />
            Add Distribution
          </Button>
        </div>

        {/* Distribution Accordions */}
        {pendingDistributions.length === 0 ? (
          <div className="border border-dashed border-border rounded-lg p-8 text-center">
            <Send className="w-12 h-12 mx-auto mb-4 text-text-muted" />
            <h4 className="font-medium mb-2">No distributions yet</h4>
            <p className="text-small text-text-muted mb-4">
              Add platforms where this post will be published. The post status will be set automatically based on distributions.
            </p>
            <Button onClick={() => setShowAddDialog(true)} disabled={availableAccounts.length === 0}>
              <Plus className="w-4 h-4 mr-2" />
              Add Distribution
            </Button>
          </div>
        ) : (
          <div className="space-y-3">
            {pendingDistributions.map((distribution) => (
              <PendingDistributionAccordionItem
                key={distribution.id}
                distribution={distribution}
                account={getAccountInfo(distribution.accountId)}
                isExpanded={expandedIds.has(distribution.id)}
                onToggle={() => handleToggle(distribution.id)}
                onUpdate={(updates) => onUpdateDistribution(distribution.id, updates)}
                onRemove={() => onRemoveDistribution(distribution.id)}
              />
            ))}
          </div>
        )}

        {/* Status info */}
        {pendingDistributions.length > 0 && (
          <div className="bg-bg-1 rounded-lg p-4 text-small text-text-muted">
            <p className="font-medium text-text mb-2">Status will be set automatically:</p>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Backlog:</strong> No distributions</li>
              <li><strong>Tagged:</strong> Has draft distributions only</li>
              <li><strong>Ongoing:</strong> Has scheduled or posted distributions</li>
              <li><strong>Complete:</strong> All distributions posted</li>
            </ul>
          </div>
        )}
      </div>

      {/* Add Distribution Dialog */}
      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>Add Distribution</DialogTitle>
            <DialogDescription>
              Select the platforms where this post will be published
            </DialogDescription>
          </DialogHeader>

          {availableAccounts.length === 0 ? (
            <div className="py-8 text-center">
              <p className="text-text-muted">
                All your accounts already have distributions for this post.
              </p>
            </div>
          ) : (
            <div className="max-h-[400px] overflow-y-auto space-y-4 py-4">
              {Object.entries(accountsByPlatform).map(([platformName, platformAccounts]) => (
                <div key={platformName}>
                  <h4 className="text-small font-medium text-text-muted mb-2">
                    {platformName}
                  </h4>
                  <div className="space-y-2">
                    {platformAccounts.map((account) => {
                      const isSelected = selectedAccountIds.includes(account.id);
                      return (
                        <label
                          key={account.id}
                          className={cn(
                            "flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-colors",
                            isSelected
                              ? "border-accent bg-accent/5"
                              : "border-border-soft hover:border-border"
                          )}
                        >
                          <Checkbox
                            checked={isSelected}
                            onCheckedChange={() => toggleAccount(account.id)}
                          />
                          <PlatformIcon
                            platformName={account.platform?.name || "blog"}
                            size="sm"
                          />
                          <div className="flex-1 min-w-0">
                            <p className="font-medium truncate">
                              {account.account_name}
                            </p>
                            <p className="text-small text-text-muted capitalize">
                              {account.account_type}
                            </p>
                          </div>
                          {isSelected && (
                            <Check className="w-4 h-4 text-accent shrink-0" />
                          )}
                        </label>
                      );
                    })}
                  </div>
                </div>
              ))}
            </div>
          )}

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowAddDialog(false);
                setSelectedAccountIds([]);
              }}
            >
              Cancel
            </Button>
            <Button
              onClick={handleAddDistributions}
              disabled={selectedAccountIds.length === 0}
            >
              Add {selectedAccountIds.length > 0 && `(${selectedAccountIds.length})`}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

// Re-export the type for use elsewhere
export type { PendingDistribution };
